spring: 
  application:
    name: chinasofti-sp-app
server:
  port: 7903
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://user:password456@localhost:8761/eureka
  instance:
    prefer-ip-address: true
feign:
   hystrix:
      enabled: false